name: g1-doggy1
implementation: wbt
type: full_body
inputs: [ ]
observation:
  obs_dict:
    actor_obs:
      - motion_command
      - motion_ref_ori_b
      - base_ang_vel
      - dof_pos
      - dof_vel
      - actions
  obs_dims:
    motion_command: 58
    motion_ref_pos_b: 3
    motion_ref_ori_b: 6
    base_lin_vel: 3
    base_ang_vel: 3
    dof_pos: 29
    dof_vel: 29
    actions: 29
  obs_scales:
    actions: 1.0
    motion_command: 1.0
    motion_ref_pos_b: 1.0
    motion_ref_ori_b: 1.0
    base_lin_vel: 1.0
    base_ang_vel: 1.0
    dof_pos: 1.0
    dof_vel: 1.0
    robot_body_pos_b: 1.0
    robot_body_ori_b: 1.0
  history_length_dict:
    actor_obs: 1
task:
  model_path: models/wbt/ppo_g1_sex.onnx
  action_mask_path: null
  rl_rate: 50.0
  policy_action_scale: 1.0
  action_scales_by_effort_limit_over_p_gain: true
  use_phase: false
  gait_period: 1.0
  skip_stiff_prompt: true
  auto_walk_on_vel_cmd: true
  use_sim_time: false
  desired_base_height: 0.75
  residual_upper_body_action: false
  print_observations: false
  motion_start_timestep: 3216
  motion_end_timestep: 3600
  motion_loop: true
  debug:
    force_upright_imu: false
    force_zero_angular_velocity: false
    force_zero_action: false
guard:
  bad_ref_ori_threshold: 0.8
  bad_lower_joint_pos_threshold: 0.8

